/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CiMail: typeof import('./src/components/icons/CiMail.vue')['default']
    Dark: typeof import('./src/components/icons/dark.vue')['default']
    DarkToggleButton: typeof import('./src/components/DarkToggleButton.vue')['default']
    LetterGlitch: typeof import('~/components/LightRays.vue')['default']
    Light: typeof import('./src/components/icons/light.vue')['default']
    LightRays: typeof import('./src/components/LightRays.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    LogosTelegram: typeof import('./src/components/icons/LogosTelegram.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillIconsDiscord: typeof import('./src/components/icons/SkillIconsDiscord.vue')['default']
    SkillIconsGithubDark: typeof import('./src/components/icons/SkillIconsGithubDark.vue')['default']
    SkillIconsGithubLight: typeof import('./src/components/icons/SkillIconsGithubLight.vue')['default']
    TagButton: typeof import('./src/components/TagButton.vue')['default']
    ToggleDarkSwitch: typeof import('./src/components/toggleDarkSwitch.vue')['default']
    VPIconMoon: typeof import('./src/components/icons/VPIconMoon.vue')['default']
    VPIconSun: typeof import('./src/components/icons/VPIconSun.vue')['default']
    VPSwitch: typeof import('./src/components/VPSwitch.vue')['default']
    WrapperIntroduction: typeof import('./src/components/WrapperIntroduction.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
