spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kintong-blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  security:
    jwt:
      key: zjt123456
      expire: 72
